Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/08/2026
Var

   msg: caractere

Inicio

      msg <- "Olá, Mundo!"
      EscrevaL(msg)
      EscrevaL("mensagem: ", msg)
      Escreva("Me livrei da maldição...")
Fimalgoritmo