Algoritmo "004"

//4) Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.

Var

   primeiro_num: inteiro
   segundo_num: inteiro
   soma: inteiro



Inicio

      Escreva("Digite um número: ")
      Leia(primeiro_num)
      Escreva("Agora digite outro: ")
      Leia(segundo_num)
      
      soma <- primeiro_num + segundo_num
      
      Escreva("A soma entre ", primeiro_num, " e ", segundo_num, " é igual a", soma)



Fimalgoritmo