Algoritmo "005"


// 5) Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
// na tela a sua média na disciplina.
// Ex:
// Nota 1: 4.5
// Nota 2: 8.5
// A média entre 4.5 e 8.5 é igual a 6.5


Var

   media, n1, n2: real


Inicio

      Escreva("Primeira nota: ")
      Leia(n1)
      Escreva("Segunda nota: ")
      Leia(n2)
      
      media <- (n1+n2)/2
      
      Escreva("A média entre", n1, " e", n2, " é igual a", media, ".")

Fimalgoritmo