Algoritmo "011"
// 11) Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
// segundo grau e mostre o valor de Delta.
Var

   A, B, C, Delta: real
   


Inicio


      Escreva("Digite o primeiro valor: ")
      Leia(A)
      Escreva("Digite o segundo valor: ")
      Leia(B)
      Escreva("Digite o terceiro valor: ")
      Leia(C)
      
      delta <- (B*B) - 4*(A*C)
      
      Escreva("O valor de Delta é igual a: ", delta)

Fimalgoritmo