Algoritmo "020"
//20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
// ÍMPAR.
Var

   numero: inteiro

Inicio

      Escreva("Digite um número e eu adivinharei se é par: ")
      Leia(numero)
      
      se (numero % 2 = 0) entao
         Escreva("O número ", numero, " é par!")
      senao
           Escreva("O número ", numero, " é ímpar!")
      fimse

Fimalgoritmo