Algoritmo "021"

// 21) Faça um algoritmo que leia um determinado ano e mostre se ele é ou não
// BISSEXTO.

Var

   ano: inteiro


Inicio


      Escreva("Digite o ano e eu direi se é bissexto: ")
      Leia(ano)
      
      se (ano % 4 = 0) entao
         Escreva("O ano de ", ano, " é bissexto!")
      senao
           Escreva("O ano de ", ano, " não é bissexto!")
      fimse
Fimalgoritmo